# Generated by Django 4.2.6 on 2023-10-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(None, 'Select User Type'), (1, 'Advisor'), (2, 'Client')], default=None, null=True),
        ),
    ]
